// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebFormForAirportPassengerRegistry.Models;

#nullable disable

namespace WebFormForAirportPassengerRegistry.Migrations
{
    [DbContext(typeof(AirportPassengerRegistryContext))]
    [Migration("20230502132924_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime");

                    b.Property<string>("PlaceOfArrival")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlaceOfDeparture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SeatsNum")
                        .HasColumnType("int");

                    b.Property<int?>("TerminalId")
                        .HasColumnType("int");

                    b.HasKey("FlightId")
                        .HasName("PK__Flights__3214EC07FA2F02A4");

                    b.HasIndex("TerminalId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.FlightTicket", b =>
                {
                    b.Property<int>("FlightTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightTicketId"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<decimal>("LuggageVolume")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("LuggageWeight")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("int");

                    b.Property<int>("Seat")
                        .HasColumnType("int");

                    b.Property<int?>("VisaId")
                        .HasColumnType("int");

                    b.HasKey("FlightTicketId")
                        .HasName("PK__FlightTi__3214EC073707D734");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("VisaId");

                    b.ToTable("FlightTickets");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("Birthplace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Communication")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Residency")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("PassengerId")
                        .HasName("PK__Passenge__3214EC07C3489574");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Search", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchId"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateSince")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sex")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("SearchId")
                        .HasName("PK__Searches__3214EC07B643ECEC");

                    b.HasIndex("PassengerId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Terminal", b =>
                {
                    b.Property<int>("TerminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerminalId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TerminalId")
                        .HasName("PK__Terminal__3214EC07DAC12DA3");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Visa", b =>
                {
                    b.Property<int>("VisaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisaId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ValidTill")
                        .HasColumnType("date");

                    b.Property<string>("VisaType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("VisaId")
                        .HasName("PK__Visas__3214EC072705346A");

                    b.ToTable("Visas");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Flight", b =>
                {
                    b.HasOne("WebFormForAirportPassengerRegistry.Terminal", "Terminal")
                        .WithMany("Flights")
                        .HasForeignKey("TerminalId")
                        .HasConstraintName("FK__Flights__Termina__440B1D61");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.FlightTicket", b =>
                {
                    b.HasOne("WebFormForAirportPassengerRegistry.Flight", "Flight")
                        .WithMany("FlightTickets")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK__FlightTic__Fligh__4D94879B");

                    b.HasOne("WebFormForAirportPassengerRegistry.Passenger", "Passenger")
                        .WithMany("FlightTickets")
                        .HasForeignKey("PassengerId")
                        .HasConstraintName("FK__FlightTic__Passe__4F7CD00D");

                    b.HasOne("WebFormForAirportPassengerRegistry.Visa", "Visa")
                        .WithMany("FlightTickets")
                        .HasForeignKey("VisaId")
                        .HasConstraintName("FK__FlightTick__Visa__4E88ABD4");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");

                    b.Navigation("Visa");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Search", b =>
                {
                    b.HasOne("WebFormForAirportPassengerRegistry.Passenger", "Passenger")
                        .WithMany("Searches")
                        .HasForeignKey("PassengerId")
                        .HasConstraintName("FK__Searches__Passen__534D60F1");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Flight", b =>
                {
                    b.Navigation("FlightTickets");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Passenger", b =>
                {
                    b.Navigation("FlightTickets");

                    b.Navigation("Searches");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Terminal", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("WebFormForAirportPassengerRegistry.Visa", b =>
                {
                    b.Navigation("FlightTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
